THEMES = {
    "dark" : {
        "color" : (45, 52, 54),
        "border_color" : (41, 128, 185),
        "box_shadow" : 1,
        "padding_w" : 20,
        "padding_h" : 20,
        "radius" : 8,
        "border_w" : 1,
        "font" : "Arial",
        "font_size" : 12,
        "font_color" : "white",
    },
    "light" : {
        "color" : (245, 246, 250),
        "border_color" : (41, 128, 185),
        "box_shadow" : 1,
        "padding_w" : 20,
        "padding_h" : 20,
        "radius" : 8,
        "border_w" : 1,
        "font" : "Arial",
        "font_size" : 12,
        "font_color" : (47, 54, 64),
    },
    "neon" : {
        "color" : (10,10,10),
        "border_color" : (41, 128, 185),
        "box_shadow" : 0,
        "padding_w" : 20,
        "padding_h" : 20,
        "radius" : 2,
        "border_w" : 1,
        "font" : "Arial",
        "font_size" : 12,
        "font_color" : (41, 128, 185),
    },
    "pink" : {
        "color" : (248, 165, 194),
        "border_color" : (247, 143, 179),
        "box_shadow" : 1,
        "padding_w" : 20,
        "padding_h" : 20,
        "radius" : 20,
        "border_w" : 2,
        "font" : "Arial",
        "font_size" : 12,
        "font_color" : (48, 57, 82),
    }
}